# Generated by Django 4.1.7 on 2023-03-27 07:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=users.models.upload_to_path,
            ),
        ),
    ]
