# Generated by Django 4.1.7 on 2023-04-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_newuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newuser",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="newuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="about",
            field=models.TextField(blank=True),
        ),
    ]
